export const PREMIUM_LANGUAGES = [
  ["en", "English"],
  ["hi", "हिन्दी"],
  ["mr", "मराठी"],
  ["bn", "বাংলা"],
  ["ta", "தமிழ்"],
  ["te", "తెలుగు"],
  ["gu", "ગુજરાતી"],
  ["kn", "ಕನ್ನಡ"],
  ["ml", "മലയാളം"],
  ["pa", "ਪੰਜਾਬੀ"],
  ["ur", "اردو"],
  ["or", "ଓଡ଼ିଆ"],
  ["as", "অসমীয়া"],
  ["ne", "नेपाली"],
  ["sa", "संस्कृत"],
  ["kok", "कोंकणी"],
  ["mai", "मैथिली"],
  ["sd", "سنڌي"],
  ["ks", "کٲشُر"],
  ["mni", "মৈতৈলোন্"],
];

const base = {
  en: {
    brandLine: "",
    navHome: "Home",
    navSchemes: "Schemes",
    navEligibility: "Eligibility",
    navDocs: "Documents",
    navLogin: "Login",
    navSignup: "Create Account",
    badge: "SEVASETU CITIZEN PROMISE",
    title1: "Government support",
    title2: "made simple for every citizen",
    subtitle:
      "Discover schemes, prepare documents, save progress and continue safely on official portals.",
    primary: "Explore Schemes",
    secondary: "Create Account",
    search: "Search schemes, scholarships, documents...",
    trust1: "Secure guidance",
    trust2: "Official portal handoff",
    trust3: "Multilingual access",
    stat1: "Scheme Records",
    stat2: "States & UTs",
    stat3: "Languages",
    stat4: "Safe Guidance",
    catTitle: "Support for every stage of life",
    catText: "Browse structured categories instead of complicated government websites.",
    authLoginTitle: "Login to SevaSetu",
    authSignupTitle: "Create your SevaSetu account",
    authSubtitle:
      "Access your dashboard, saved schemes, document readiness and eligibility guidance.",
    email: "Email address",
    password: "Password",
    name: "Full name",
    mobile: "Mobile number",
    state: "State",
    otp: "Continue with OTP",
    google: "Continue with Google",
    loginBtn: "Login",
    signupBtn: "Create Account",
    switchToSignup: "New to SevaSetu?",
    switchToLogin: "Already have an account?",
    quote:
      "Every citizen deserves simple, clear and trusted access to government support.",
    official: "Official services",
  },
  hi: {
    brandLine: "नागरिकों को जोड़ना, जीवन को सशक्त बनाना",
    navHome: "होम",
    navSchemes: "योजनाएँ",
    navEligibility: "पात्रता",
    navDocs: "दस्तावेज़",
    navLogin: "लॉगिन",
    navSignup: "खाता बनाएँ",
    badge: "सेवासेतु नागरिक वादा",
    title1: "सरकारी सहायता",
    title2: "हर नागरिक के लिए सरल",
    subtitle:
      "योजनाएँ खोजें, दस्तावेज़ तैयार करें, प्रगति सेव करें और आधिकारिक पोर्टल पर सुरक्षित रूप से आगे बढ़ें।",
    primary: "योजनाएँ देखें",
    secondary: "खाता बनाएँ",
    search: "योजनाएँ, छात्रवृत्ति, दस्तावेज़ खोजें...",
    trust1: "सुरक्षित मार्गदर्शन",
    trust2: "आधिकारिक पोर्टल लिंक",
    trust3: "बहुभाषी सुविधा",
    stat1: "योजना रिकॉर्ड",
    stat2: "राज्य और केंद्रशासित प्रदेश",
    stat3: "भाषाएँ",
    stat4: "सुरक्षित मार्गदर्शन",
    catTitle: "जीवन के हर चरण के लिए सहायता",
    catText: "जटिल सरकारी वेबसाइटों की जगह व्यवस्थित श्रेणियों से योजनाएँ देखें।",
    authLoginTitle: "सेवासेतु में लॉगिन करें",
    authSignupTitle: "सेवासेतु खाता बनाएँ",
    authSubtitle:
      "डैशबोर्ड, सेव योजनाएँ, दस्तावेज़ तैयारी और पात्रता मार्गदर्शन देखें।",
    email: "ईमेल पता",
    password: "पासवर्ड",
    name: "पूरा नाम",
    mobile: "मोबाइल नंबर",
    state: "राज्य",
    otp: "OTP से जारी रखें",
    google: "Google से जारी रखें",
    loginBtn: "लॉगिन",
    signupBtn: "खाता बनाएँ",
    switchToSignup: "सेवासेतु पर नए हैं?",
    switchToLogin: "पहले से खाता है?",
    quote:
      "हर नागरिक को सरकारी सहायता तक सरल, स्पष्ट और भरोसेमंद पहुँच मिलनी चाहिए।",
    official: "आधिकारिक सेवाएँ",
  },
  mr: {
    brandLine: "नागरिकांना जोडणे, जीवन सक्षम करणे",
    navHome: "मुख्यपृष्ठ",
    navSchemes: "योजना",
    navEligibility: "पात्रता",
    navDocs: "कागदपत्रे",
    navLogin: "लॉगिन",
    navSignup: "खाते तयार करा",
    badge: "सेवासेतु नागरिक वचन",
    title1: "सरकारी मदत",
    title2: "प्रत्येक नागरिकासाठी सोपी",
    subtitle:
      "योजना शोधा, कागदपत्रे तयार करा, प्रगती जतन करा आणि अधिकृत पोर्टलवर सुरक्षितपणे पुढे जा.",
    primary: "योजना पाहा",
    secondary: "खाते तयार करा",
    search: "योजना, शिष्यवृत्ती, कागदपत्रे शोधा...",
    trust1: "सुरक्षित मार्गदर्शन",
    trust2: "अधिकृत पोर्टल लिंक",
    trust3: "बहुभाषिक सुविधा",
    stat1: "योजना नोंदी",
    stat2: "राज्ये व केंद्रशासित प्रदेश",
    stat3: "भाषा",
    stat4: "सुरक्षित मार्गदर्शन",
    catTitle: "जीवनाच्या प्रत्येक टप्प्यासाठी मदत",
    catText: "किचकट सरकारी वेबसाइटऐवजी व्यवस्थित श्रेणींमधून योजना पाहा.",
    authLoginTitle: "सेवासेतु लॉगिन",
    authSignupTitle: "सेवासेतु खाते तयार करा",
    authSubtitle:
      "डॅशबोर्ड, सेव योजना, कागदपत्र तयारी आणि पात्रता मार्गदर्शन मिळवा.",
    email: "ईमेल पत्ता",
    password: "पासवर्ड",
    name: "पूर्ण नाव",
    mobile: "मोबाइल नंबर",
    state: "राज्य",
    otp: "OTP ने सुरू ठेवा",
    google: "Google ने सुरू ठेवा",
    loginBtn: "लॉगिन",
    signupBtn: "खाते तयार करा",
    switchToSignup: "सेवासेतुवर नवीन आहात?",
    switchToLogin: "आधीच खाते आहे?",
    quote:
      "प्रत्येक नागरिकाला सरकारी मदतीपर्यंत सोपी, स्पष्ट आणि विश्वसनीय पहुँच मिळाली पाहिजे.",
    official: "अधिकृत सेवा",
  },
};

const names = {
  bn: "বাংলা",
  ta: "தமிழ்",
  te: "తెలుగు",
  gu: "ગુજરાતી",
  kn: "ಕನ್ನಡ",
  ml: "മലയാളം",
  pa: "ਪੰਜਾਬੀ",
  ur: "اردو",
  or: "ଓଡ଼ିଆ",
  as: "অসমীয়া",
  ne: "नेपाली",
  sa: "संस्कृत",
  kok: "कोंकणी",
  mai: "मैथिली",
  sd: "سنڌي",
  ks: "کٲشُر",
  mni: "মৈতৈলোন্",
};

function translatedFallback(code) {
  const langName = names[code] || "Selected Language";
  return {
    ...base.en,
    brandLine: `${langName} • Citizen services`,
    badge: `${langName} SevaSetu`,
    title1: "SevaSetu",
    title2: `${langName} mode enabled`,
    subtitle:
      "This page is connected to the selected language mode. Core navigation and service access stay active.",
    primary: "Open Schemes",
    secondary: "Create Account",
    authLoginTitle: `Login • ${langName}`,
    authSignupTitle: `Create Account • ${langName}`,
    authSubtitle:
      "Continue to dashboard, saved schemes, document readiness and eligibility guidance.",
  };
}

export function premiumText(language = "en") {
  const code = String(language || "en").trim();
  return base[code] || translatedFallback(code);
}

export function isRtlLanguage(language = "en") {
  return ["ur", "sd", "ks"].includes(language);
}
